name: Auto Generate At-RTOS Version
on: [push, pull_request]

jobs:
  Auto-Version:
    name: Generate At-RTOS Version
    runs-on: windows-latest
    steps:

      - name: Execute Version Script
        shell: powershell
        working-directory: script
        run: |
          .\version.cmd
